version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
      - libmagic-dev

sphinx:
  configuration: docs/conf.py

python:
    install:
    - requirements: requirements.txt
